### PR TITLE
Fix for #42

### PR DESCRIPTION
**Pull request by IRus**

### CODE REVIEW

**Comment by coolkit-tony** [comment]
Hi, @IRus. You should replace `yourHomeAssitantLongLivedAccessToken` with your real token.

**Comment by coolkit-tony** [comment]
Hi, @IRus. You should replace `yourHomeAssitantLongLivedAccessToken` with your real token.

**Comment by IRus** [comment]
Exactly, but README doesn't contain this info, hence this PR

**Comment by IRus** [comment]
This configuration is not clear for people that runs this container without HACS or supervisor.
See #42

**Comment by coolkit-tony** [comment]
Your opinion is fully noted. We will merge your code soon. Thanks for your PR!

**Pull request merged**
